# Docker Compose for PromptPulse Development Environment
# Optional alternative to running services locally

version: '3.8'

services:
  # Node.js API Server
  api-server:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - LOG_LEVEL=debug
    volumes:
      - .:/app:ro
      - /app/node_modules
      - ./.env:/app/.env:ro
    networks:
      - promptpulse-network

  # Next.js Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NODE_ENV=development
    volumes:
      - ./client:/app:ro
      - /app/node_modules
      - /app/.next
    depends_on:
      - api-server
    networks:
      - promptpulse-network


networks:
  promptpulse-network:
    driver: bridge